name: Build and Push Docker Image

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:                          # <-- ДОБАВЬТЕ ЭТОТ БЛОК
      contents: read                      # Чтение кода репозитория
      packages: write                     # Запись в GitHub Container Registry

    steps:
      - uses: actions/checkout@v4
      
      - name: Convert to lowercase
        id: lowercase
        run: |
          echo "IMAGE_NAME=ghcr.io/$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.lowercase.outputs.IMAGE_NAME }}:latest
            ${{ steps.lowercase.outputs.IMAGE_NAME }}:${{ github.sha }}
